/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#855300',
        'primary-container': '#f59e0b',
        'on-primary': '#ffffff',
        'on-primary-container': '#613b00',
        'primary-fixed': '#ffddb8',
        'primary-fixed-dim': '#ffb95f',
        secondary: '#50616b',
        'secondary-container': '#d3e5f1',
        'secondary-fixed': '#d3e5f1',
        'secondary-fixed-dim': '#b7c9d5',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#566771',
        'on-secondary-fixed': '#0c1e26',
        'on-secondary-fixed-variant': '#384953',
        tertiary: '#bf0715',
        'tertiary-container': '#ff9388',
        'tertiary-fixed': '#ffdad6',
        'tertiary-fixed-dim': '#ffb4ab',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#8d000b',
        'on-tertiary-fixed': '#410002',
        'on-tertiary-fixed-variant': '#93000b',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        surface: '#f9f9ff',
        'surface-container': '#e7eeff',
        'surface-container-low': '#f0f3ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#dee8ff',
        'surface-container-highest': '#d8e3fb',
        'surface-variant': '#d8e3fb',
        'surface-dim': '#cfdaf2',
        'surface-bright': '#f9f9ff',
        'surface-tint': '#855300',
        'on-surface': '#111c2d',
        'on-surface-variant': '#534434',
        'on-background': '#111c2d',
        background: '#f9f9ff',
        outline: '#867461',
        'outline-variant': '#d8c3ad',
        'inverse-primary': '#ffb95f',
        'inverse-surface': '#263143',
        'inverse-on-surface': '#ecf1ff',
        'on-primary-fixed': '#2a1700',
        'on-primary-fixed-variant': '#653e00',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['"Outfit"', '"Plus Jakarta Sans"', 'sans-serif'],
        brand: ['"Outfit"', 'sans-serif'],
        heading: ['"Outfit"', '"Plus Jakarta Sans"', 'sans-serif'],
      },
      spacing: {
        'inset-xs': '0.5rem',
        'inset-sm': '0.75rem',
        'inset-md': '1rem',
        'inset-lg': '1.5rem',
        'inset-xl': '2rem',
        'stack-sm': '0.75rem',
        'stack-md': '1.25rem',
        'stack-lg': '2rem',
        'gutter-mobile': '1rem',
        'gutter-desktop': '2rem',
        'touch-min': '3rem',
        'touch-lg': '3.5rem',
      },
      fontSize: {
        'label-sm': ['13px', { lineHeight: '18px', letterSpacing: '0.03em', fontWeight: '700' }],
        'label-md': ['15px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-lg': ['18px', { lineHeight: '24px', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '0em', fontWeight: '700' }],
        'headline-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
